 
	DROP TABLE IF EXISTS AC_UI_PROPERTY, AC_UI_SEQUENCER ;
	 
	DROP TABLE IF EXISTS AC_UI_USER, AC_UI_ROLE, AC_UI_USER_ROLES, AC_UI_USER_LOGIN_TOKEN ;	
	 
	DROP TABLE IF EXISTS AC_UI_COMPANY, AC_UI_COMPANY_PROPERTY ;
	
	DROP TABLE IF EXISTS AC_UI_MENU, AC_UI_MENU_PROPERTY, AC_UI_MENU_ITEM, AC_UI_MENU_ITEM_PROPERTY ;
		
	DROP TABLE IF EXISTS AC_UI_AVATAR_IMAGE, AC_UI_AVATAR_IMAGE_DATA  ;
	
	 
	DROP TABLE IF EXISTS AC_UI_PAGE, AC_UI_PAGE_BODY, AC_UI_PAGE_BODY_VERSION, AC_UI_PAGE_VERSION , AC_UI_PAGE_PROPERTY ;	
	 
	DROP TABLE IF EXISTS AC_UI_API , AC_UI_API_PROPERTY ;
 
	DROP TABLE IF EXISTS AC_UI_VIEWCOUNT  ;
	    	
	DROP TABLE IF EXISTS AC_UI_IMAGE , AC_UI_IMAGE_PROPERTY, AC_UI_IMAGE_DATA, AC_UI_IMAGE_LINK ;
 
	DROP TABLE IF EXISTS AC_UI_SHARED_LINK ;
	 
DROP TABLE IF EXISTS AC_UI_ATTACHMENT , AC_UI_ATTACHMENT_DATA , AC_UI_ATTACHMENT_PROPERTY;

DROP TABLE IF EXISTS AC_UI_TAG, AC_UI_OBJECT_TAG, AC_UI_TAG_PROPERTY;

DROP TABLE IF EXISTS acl_entry , acl_object_identity , acl_class, acl_sid;

			   	