	-- =================================================  
	-- PACKAGE   : UI  
	-- COMPONENT : RESOURCE ASSET
	-- CREATE    : 2021.05.31
	-- UPDATE    : 
	-- =================================================	
  	
	CREATE TABLE AC_UI_ASSETS
    (	
	ASSET_ID				INTEGER NOT NULL COMMENT 'ASSET ID', 
	OBJECT_ID				INTEGER NOT NULL COMMENT 'OBJECT ID', 
	OBJECT_TYPE				INTEGER NOT NULL COMMENT 'OBJECT TYPE', 
	LINK_ID					VARCHAR(255) NOT NULL COMMENT'유일한 랜덤 키', 
	FILE_NAME				VARCHAR(255) NOT NULL COMMENT '파일 이름', 
	FILE_SIZE				INTEGER	NOT NULL COMMENT  'File Size',
	DESCRIPTION             VARCHAR(1000) COMMENT '설명',
	ENABLED          		TINYINT  DEFAULT 1 COMMENT  'ENABLED 여부',
	SECURED          		TINYINT  DEFAULT 1 COMMENT  'SECURED 여부',
	USER_ID					INTEGER	NOT NULL COMMENT  '생성자 ID',
	CREATION_DATE			DATETIME NULL COMMENT '생성일자',
	MODIFIED_DATE			DATETIME NULL COMMENT '수정일자',	
	CONSTRAINT AC_UI_ASSETS_PK PRIMARY KEY (ASSET_ID)
    ) ;
   
    CREATE INDEX AC_UI_ASSETS_IDX_01 ON AC_UI_ASSETS ( OBJECT_TYPE, OBJECT_ID);
    CREATE INDEX AC_UI_ASSETS_IDX_02 ON AC_UI_ASSETS ( LINK_ID );
    
	CREATE TABLE AC_UI_ASSETS_DATA ( 
      ASSET_ID  INTEGER COMMENT 'ID',
	  ASSET_DATA LONGBLOB COMMENT 'ASSET 데이터' ,
	  CONSTRAINT AC_UI_ASSETS_DATA_PK PRIMARY KEY (ASSET_ID)
	) ;
 
	ALTER TABLE AC_UI_ASSETS_DATA  COMMENT 'ASSET 데이터 테이블'; 
  
   
    CREATE TABLE AC_UI_ASSETS_PROPERTY (
	 ASSET_ID             INTEGER NOT NULL COMMENT 'ID',
	 PROPERTY_NAME         VARCHAR(100)   NOT NULL COMMENT '프로퍼티 이름',
	 PROPERTY_VALUE        VARCHAR(1024)  NOT NULL COMMENT '프로퍼티 값',
	 CONSTRAINT AC_UI_ASSETS_PROPERTY_PK PRIMARY KEY (ASSET_ID, PROPERTY_NAME)
    );	
		
	ALTER TABLE AC_UI_ASSETS_PROPERTY  COMMENT 'ASSET 프로퍼티 테이블';   