	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : PHOTO ALBUMS
	-- CREATE : 2020.04.06
	-- UPDATE : 2020.06.23
	-- =================================================	
	
	DROP TABLE IF EXISTS AC_UI_ALBUM, AC_UI_ALBUM_PROPERTY, AC_UI_ALBUM_IMAGES ;
	
	CREATE TABLE AC_UI_ALBUM (
		ALBUM_ID               INTEGER NOT NULL COMMENT '카테고리 ID',
		NAME				   VARCHAR(255) NOT NULL COMMENT '이름',  
	 	DESCRIPTION            VARCHAR(2000) COMMENT '설명',
	 	USER_ID				   INTEGER NOT NULL COMMENT 'CREATOR',	 	
	  	CREATION_DATE          DATETIME DEFAULT  NOW() NOT NULL COMMENT '생성일자',
	  	MODIFIED_DATE          DATETIME DEFAULT  NOW() NOT NULL COMMENT '수정일자',	
	 	CONSTRAINT AC_UI_ALBUM_PK PRIMARY KEY (ALBUM_ID)
	);
	ALTER TABLE AC_UI_ALBUM  COMMENT 'IMAGE ALBUM 테이블'; 
			
	CREATE TABLE AC_UI_ALBUM_PROPERTY (
		ALBUM_ID             	INTEGER NOT NULL COMMENT 'ID',
		PROPERTY_NAME         VARCHAR(100)   NOT NULL COMMENT '프로퍼티 이름',
		PROPERTY_VALUE        VARCHAR(1024)  NOT NULL COMMENT '프로퍼티 값',
		CONSTRAINT AC_UI_ALBUM_PROPERTY_PK PRIMARY KEY (ALBUM_ID, PROPERTY_NAME)
	);	
		
	ALTER TABLE `AC_UI_ALBUM_PROPERTY`  COMMENT 'ALBUM 프로퍼티 테이블';
		
	CREATE TABLE AC_UI_ALBUM_IMAGES (
		ALBUM_ID               INTEGER NOT NULL COMMENT 'ALBUM ID', 
		IMAGE_ID 			   INTEGER NOT NULL COMMENT 'IMAGE ID',
		SORT_ORDER			   INTEGER NOT NULL,
		CONSTRAINT AC_UI_ALBUM_IMAGES_PK PRIMARY KEY (ALBUM_ID, IMAGE_ID) 
	);
	
	ALTER TABLE AC_UI_ALBUM_IMAGES  COMMENT 'IMAGE ALBUM IMAGES'; 
	
	-- ADDED 2012.06.23
	
	CREATE TABLE AC_UI_ALBUM_CONTENTS (
		ALBUM_ID               INTEGER NOT NULL COMMENT 'ALBUM ID', 
		CONTENT_TYPE           INTEGER NOT NULL COMMENT 'CONTENT TYPE',
		CONTENT_ID 			   INTEGER NOT NULL COMMENT 'CONTENT ID',
		SORT_ORDER			   INTEGER NOT NULL,
		CONSTRAINT AC_UI_ALBUM_CONTENTS_PK PRIMARY KEY (ALBUM_ID, CONTENT_TYPE, CONTENT_ID) 
	);
	
	ALTER TABLE AC_UI_ALBUM_CONTENTS  COMMENT 'ALBUM CONTENTS'; 
	