
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (1,'USER', '사용자', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (2,'GROUP', '그룹', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (3,'COMPANY', '회사', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (4,'ROLE', '권한', 5);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (5,'CATEGORY', '카테고리', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (8,'COMMENT', '댓글', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (9,'TAG', '태그', 1); 
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (10,'ATTACHMENT', '파일', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (11,'IMAGE', '이미지', 1);
--Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (12,'LOGO_IMAGE', '로고 이미지', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (13,'AVATAR_IMAGE' , '프로필 이미지', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (14,'PAGE', '페이지', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (15,'MENU', '메뉴', 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (16,'MENU_ITEM', null , 1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (30,'API','REST API',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (41,'ANNOUNCE','공지',1);

Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (20,'STREAMS','스트림',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (21,'STREAMS_THREAD','스트림 스레드',1);
Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (22,'STREAMS_MESSAGE','스트림 글',1);

Insert into AC_UI_SEQUENCER (SEQUENCER_ID,NAME, DISPLAY_NAME, VALUE) values (35,'I18N','I18N',1);


Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (1,'ROLE_ADMINISTRATOR','관리자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (2,'ROLE_DEVELOPER','개발자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (3,'ROLE_OPERATOR', '운영자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (4,'ROLE_USER', '일반 사용자 롤');
